name: Upload Python Package

on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install build
          pip install -r requirements.txt
          pip install -r requirements_mkdocs.txt

      - name: Run unit tests
        run: python -m unittest

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python for Docs
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

  - name: Checkout ArgoCD repository
        uses: actions/checkout@v4
        with:
          repository: ARAldhafeeri/zenaura
          path: main
          token: ${{ secrets.REPO_TOKEN }}

      - name: deploy mkdocs
        id: cache-mkdocs
        
        run: | 
        # setup identity 
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        # Ensure the repository is up to date
        git pull 
        mkdocs gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
